-- Migration 0004: sessions + session_turns + RLS (Phase 1 Task 2).
--
-- Schema portion was generated by `npx drizzle-kit generate` from the
-- declarations in `src/db/schema/sessions.ts` and `session-turns.ts`,
-- then hand-wrapped in idempotent guards (IF NOT EXISTS / DO blocks)
-- so re-running via `scripts/apply-custom-migrations.ts` is safe. The
-- RLS block at the bottom is hand-written per the Phase 1 plan §Step 2
-- (drizzle-kit doesn't manage policies).

DO $$ BEGIN
  CREATE TYPE "public"."session_status" AS ENUM('active', 'completed');
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_id" uuid NOT NULL,
	"brain_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"status" "session_status" DEFAULT 'active' NOT NULL,
	"turn_count" integer DEFAULT 0 NOT NULL,
	"input_tokens" integer DEFAULT 0 NOT NULL,
	"output_tokens" integer DEFAULT 0 NOT NULL,
	"total_tokens" integer DEFAULT 0 NOT NULL,
	"first_message" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_active_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "session_turns" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"session_id" uuid NOT NULL,
	"turn_number" integer NOT NULL,
	"user_message" jsonb NOT NULL,
	"assistant_messages" jsonb NOT NULL,
	"tool_calls" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"input_tokens" integer DEFAULT 0 NOT NULL,
	"output_tokens" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "sessions" ADD CONSTRAINT "sessions_company_id_companies_id_fk"
    FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id")
    ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "sessions" ADD CONSTRAINT "sessions_brain_id_brains_id_fk"
    FOREIGN KEY ("brain_id") REFERENCES "public"."brains"("id")
    ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id")
    ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "session_turns" ADD CONSTRAINT "session_turns_session_id_sessions_id_fk"
    FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id")
    ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "sessions_user_last_active_idx"
  ON "sessions" USING btree ("user_id","last_active_at");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "sessions_status_last_active_idx"
  ON "sessions" USING btree ("status","last_active_at");
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "session_turns_session_turn_idx"
  ON "session_turns" USING btree ("session_id","turn_number");
--> statement-breakpoint

-- --------------------------------------------------------------------
-- Row-Level Security policies (Phase 1 Task 2 plan §Step 2).
--
-- `sessions` enforces BOTH company isolation AND per-user ownership:
-- a user only sees their own sessions, even from other members of the
-- same company. Chat history is private.
--
-- `session_turns` inherits its boundary from the parent session — the
-- subquery hits the `sessions` policy transitively.
--
-- Idempotent: DROP IF EXISTS + CREATE so re-running this migration via
-- scripts/apply-custom-migrations.ts is safe.
-- --------------------------------------------------------------------

ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "sessions_company_user" ON "sessions";
CREATE POLICY "sessions_company_user" ON "sessions"
  FOR ALL
  USING (
    company_id IN (
      SELECT company_id FROM users
      WHERE id = auth.uid() AND status = 'active'
    )
    AND user_id = auth.uid()
  );

ALTER TABLE "session_turns" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "session_turns_via_session" ON "session_turns";
CREATE POLICY "session_turns_via_session" ON "session_turns"
  FOR ALL
  USING (
    session_id IN (
      SELECT id FROM sessions WHERE user_id = auth.uid()
    )
  );
