// Phase 0 end-to-end integration test.
//
// Exercises the full Pre-MVP story: a brand-new company can be created +
// seeded, documents read via MCP with YAML frontmatter, edited via
// direct DB writes (dashboard parity), manifest regenerated, change
// history surfaced via MCP, token revocation respected, and audit rows
// logged for both authentication and document access.
//
// Runs against live Supabase via the Drizzle superuser connection.
//
// NOTE (Task 10 / Task 16): The universal pack v1 ships 7 folders and zero
// seeded documents. Tests that previously relied on a 10-doc seed (e.g. the
// brand-voice-tone slug) now insert a fixture document in beforeAll and
// assert against that. The seed contract tested here is:
//   - 7 folders are created
//   - 0 documents are seeded
//   - 1 current navigation manifest exists after seed
// Commit ca3d531 is the canonical reference for this change.

import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { and, eq } from 'drizzle-orm';

import { db } from '@/db';
import {
  auditEvents,
  documents,
  documentVersions,
  folders,
  navigationManifests,
} from '@/db/schema';
import { flushEvents } from '@/lib/audit/logger';
import { regenerateManifest } from '@/lib/brain/manifest';
import { handleToolCall } from '@/lib/mcp/handler';
import { revokeToken } from '@/lib/auth/tokens';

import {
  cleanupCompany,
  createSeededCompany,
  createTestToken,
  type TestCompany,
} from './helpers';

let company: TestCompany;
let token: string;
let tokenId: string;
// Fixture document inserted in beforeAll so search + get_document tests
// have a concrete doc to assert against (the universal pack seeds 0 docs).
let fixtureDocId: string;
let fixtureDocPath: string;

beforeAll(async () => {
  company = await createSeededCompany('phase0');
  const t = await createTestToken(company.companyId, company.userId);
  token = t.token;
  tokenId = t.tokenId;

  // Find the first folder seeded by the universal pack so we can hang a
  // fixture document off it.
  const [firstFolder] = await db
    .select({ id: folders.id })
    .from(folders)
    .where(eq(folders.brainId, company.brainId))
    .limit(1);
  expect(firstFolder).toBeDefined();

  // Insert a single fixture doc whose title/content includes the word "voice"
  // so the search tests can find something meaningful.
  const [inserted] = await db
    .insert(documents)
    .values({
      companyId: company.companyId,
      brainId: company.brainId,
      folderId: firstFolder.id,
      title: 'Brand Voice & Tone',
      slug: 'brand-voice-tone',
      path: 'company/brand-voice-tone',
      content:
        '# Brand Voice & Tone\n\nOur brand voice is warm, direct, and confident.',
      status: 'draft',
      isCore: true,
      confidenceLevel: 'medium',
      topics: ['brand', 'voice'],
      type: 'canonical',
    })
    .returning({ id: documents.id, path: documents.path });
  fixtureDocId = inserted.id;
  fixtureDocPath = inserted.path;
}, 60_000);

afterAll(async () => {
  await cleanupCompany(company);
}, 60_000);

function mcpRequest(): Request {
  return new Request('http://localhost/api/mcp', {
    method: 'POST',
    headers: {
      authorization: `Bearer ${token}`,
      'content-type': 'application/json',
    },
    body: JSON.stringify({}),
  });
}

describe('Phase 0 end-to-end', () => {
  it('seeds 7 folders + 0 documents + 1 current manifest (universal pack v1)', async () => {
    // v1 universal pack: 7 top-level folders, 0 seeded documents. Manifest
    // is regenerated by seedBrainFromUniversalPack even with 0 docs.
    const manifests = await db
      .select()
      .from(navigationManifests)
      .where(
        and(
          eq(navigationManifests.brainId, company.brainId),
          eq(navigationManifests.isCurrent, true),
        ),
      );
    expect(manifests).toHaveLength(1);

    const seededFolders = await db
      .select()
      .from(folders)
      .where(eq(folders.brainId, company.brainId));
    expect(seededFolders).toHaveLength(7);

    // The fixture doc (inserted in beforeAll) is NOT a seeded doc — confirm
    // the seed itself wrote zero documents.
    const seededDocs = await db
      .select()
      .from(documents)
      .where(
        and(
          eq(documents.brainId, company.brainId),
          eq(documents.isCore, false),
        ),
      );
    // Only the fixture doc (isCore=true) exists; seeded core docs = 0.
    const allDocs = await db
      .select()
      .from(documents)
      .where(
        and(
          eq(documents.brainId, company.brainId),
          eq(documents.slug, '__seed_marker_that_does_not_exist__'),
        ),
      );
    // A direct query: total docs minus the fixture doc we just inserted.
    // Simplest assertion: fixture is the only isCore doc.
    const coreDocs = await db
      .select()
      .from(documents)
      .where(
        and(
          eq(documents.brainId, company.brainId),
          eq(documents.isCore, true),
        ),
      );
    // Only the fixture doc we inserted is isCore=true — the pack seeded 0.
    expect(coreDocs).toHaveLength(1);
    expect(coreDocs[0].slug).toBe('brand-voice-tone');

    // Validate seeded folders are from the universal pack.
    const slugs = seededFolders.map((f) => f.slug).sort();
    expect(slugs).toEqual([
      'company',
      'customers',
      'market',
      'marketing',
      'operations',
      'product',
      'signals',
    ]);
    void seededDocs; // referenced to avoid lint warning
    void allDocs;
  });

  it('MCP search_documents returns matching documents', async () => {
    const res = await handleToolCall({
      toolName: 'search_documents',
      rawInput: { query: 'voice' },
      request: mcpRequest(),
    });
    expect(res.isError).toBeFalsy();
    expect(res.content[0]?.type).toBe('text');
    const body = JSON.parse(res.content[0].text) as {
      query: string;
      results: Array<{ path: string; title: string }>;
    };
    expect(body.query).toBe('voice');
    expect(Array.isArray(body.results)).toBe(true);
    expect(body.results.length).toBeGreaterThan(0);
    // The fixture doc (brand-voice-tone) must be among the hits.
    expect(body.results.some((r) => r.path.includes('brand-voice-tone'))).toBe(
      true,
    );
  });

  it('MCP get_document prefixes YAML frontmatter', async () => {
    const [fixtureDoc] = await db
      .select()
      .from(documents)
      .where(
        and(
          eq(documents.brainId, company.brainId),
          eq(documents.slug, 'brand-voice-tone'),
        ),
      )
      .limit(1);
    expect(fixtureDoc).toBeDefined();

    const res = await handleToolCall({
      toolName: 'get_document',
      rawInput: { path: fixtureDoc.path },
      request: mcpRequest(),
    });
    expect(res.isError).toBeFalsy();
    expect(res.content[0]?.type).toBe('text');

    const body = JSON.parse(res.content[0].text) as {
      document: { content: string; path: string };
    };
    const content = body.document.content;
    expect(content).toMatch(/^---\s*\n/);
    expect(content).toContain('status: draft');
    expect(content).toContain('is_core: true');
    expect(content).toContain('confidence_level: medium');
    expect(body.document.path).toBe(fixtureDoc.path);
  });

  it('dashboard-style PATCH creates version + keeps one current manifest', async () => {
    const [doc] = await db
      .select()
      .from(documents)
      .where(
        and(
          eq(documents.brainId, company.brainId),
          eq(documents.isCore, true),
        ),
      )
      .limit(1);
    expect(doc).toBeDefined();

    const before = await db
      .select()
      .from(documentVersions)
      .where(eq(documentVersions.documentId, doc.id));

    const nextVersion = doc.version + 1;
    const nextContent = doc.content + '\n\nUpdated by e2e.';

    await db
      .update(documents)
      .set({
        content: nextContent,
        version: nextVersion,
        updatedAt: new Date(),
      })
      .where(eq(documents.id, doc.id));

    await db.insert(documentVersions).values({
      companyId: company.companyId,
      documentId: doc.id,
      versionNumber: nextVersion,
      content: nextContent,
      changeSummary: 'e2e edit',
      changedBy: company.userId,
      changedByType: 'human',
    });

    await regenerateManifest(company.brainId);

    const after = await db
      .select()
      .from(documentVersions)
      .where(eq(documentVersions.documentId, doc.id));
    expect(after.length).toBe(before.length + 1);

    const currentManifests = await db
      .select()
      .from(navigationManifests)
      .where(
        and(
          eq(navigationManifests.brainId, company.brainId),
          eq(navigationManifests.isCurrent, true),
        ),
      );
    expect(currentManifests).toHaveLength(1);
  });

  it('MCP get_diff_history surfaces recent edits', async () => {
    const since = new Date(Date.now() - 5 * 60_000).toISOString();
    const res = await handleToolCall({
      toolName: 'get_diff_history',
      rawInput: { since },
      request: mcpRequest(),
    });
    expect(res.isError).toBeFalsy();
    expect(res.content[0]?.type).toBe('text');
    // Shape of get_diff_history is not asserted strictly here — the
    // tool's own unit tests cover that. We just need the MCP envelope
    // to come back successful for a valid `since` filter.
    const body = JSON.parse(res.content[0].text) as unknown;
    expect(body).toBeDefined();
  });

  it('audit_events rows were logged for auth + document access', async () => {
    await flushEvents();
    const events = await db
      .select()
      .from(auditEvents)
      .where(eq(auditEvents.companyId, company.companyId));
    expect(events.length).toBeGreaterThan(0);
    const categories = new Set(events.map((e) => e.category));
    // Token.used events fire inside authenticateAgentToken on every
    // successful call — those land as category = 'authentication'.
    expect(categories.has('authentication')).toBe(true);
    // Tool executor fires a document_access event on every call.
    expect(categories.has('document_access')).toBe(true);
  });

  it('revoked token is rejected by MCP', async () => {
    await revokeToken(tokenId);

    const res = await handleToolCall({
      toolName: 'search_documents',
      rawInput: { query: 'anything' },
      request: mcpRequest(),
    });
    expect(res.isError).toBe(true);
    const body = JSON.parse(res.content[0].text) as {
      code: string;
      message: string;
    };
    expect(body.code).toBe('invalid_token');
  });
});

// Keep these exported refs accessible if any downstream test imports them.
export { fixtureDocId, fixtureDocPath };
