/**
 * Apply the hand-written SQL migrations that Drizzle Kit does not manage.
 *
 * Drizzle Kit's `push` only applies the schema declared in TypeScript.
 * Postgres triggers, RLS policies, and the search_vector function live in
 * hand-written SQL files under src/db/migrations. This script executes
 * those files in order against DATABASE_URL.
 *
 * Usage:
 *   npx tsx scripts/apply-custom-migrations.ts
 *
 * Each SQL file is written to be idempotent (DROP IF EXISTS + CREATE OR
 * REPLACE) so re-running this script is safe.
 */

import 'dotenv/config';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import postgres from 'postgres';

// Hand-written migrations, applied in order. 0001 is Drizzle-generated
// and handled by drizzle-kit; we skip it here. 0004 was generated by
// drizzle-kit and then hand-augmented with idempotent guards plus an
// RLS policy block — we run it through this script too so the RLS
// portion lands. The CREATE TABLE statements use IF NOT EXISTS / DO
// blocks so re-running on top of `drizzle-kit push` is safe.
const CUSTOM_MIGRATIONS = [
  '0002_tsvector_trigger.sql',
  '0003_rls_policies.sql',
  '0004_sessions.sql',
  '0005_mcp_connections.sql',
  '0006_document_type_column.sql',
  '0007_agents_ingestion.sql',
  '0008_skill_manifests_select_only.sql',
  '0009_session_attachments_owner_scope.sql',
  '0010_attachment_storage.sql',
  '0012_audit_events_mcp_invocation_enum.sql',
];

async function main() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error('DATABASE_URL is not set');
  }

  const sql = postgres(connectionString, { max: 1 });

  try {
    for (const filename of CUSTOM_MIGRATIONS) {
      const path = resolve(__dirname, '..', 'src', 'db', 'migrations', filename);
      const content = readFileSync(path, 'utf8');
      console.log(`Applying ${filename}...`);
      await sql.unsafe(content);
      console.log(`  ✓ ${filename} applied`);
    }
  } finally {
    await sql.end();
  }
}

main().catch((err) => {
  console.error('Migration failed:', err);
  process.exit(1);
});
