/**
 * Apply the hand-written SQL migrations that Drizzle Kit does not manage.
 *
 * Drizzle Kit's `push` only applies the schema declared in TypeScript.
 * Postgres triggers, RLS policies, and the search_vector function live in
 * hand-written SQL files under src/db/migrations. This script executes
 * those files in order against DATABASE_URL.
 *
 * Usage:
 *   npx tsx scripts/apply-custom-migrations.ts
 *
 * Each SQL file is written to be idempotent (DROP IF EXISTS + CREATE OR
 * REPLACE) so re-running this script is safe.
 */

import 'dotenv/config';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import postgres from 'postgres';

// Hand-written migrations, applied in order. 0001 is Drizzle-generated
// and handled by drizzle-kit; we skip it here. 0004 was generated by
// drizzle-kit and then hand-augmented with idempotent guards plus an
// RLS policy block — we run it through this script too so the RLS
// portion lands. The CREATE TABLE statements use IF NOT EXISTS / DO
// blocks so re-running on top of `drizzle-kit push` is safe.
//
// 0008 is intentionally omitted: it narrowed the `skill_manifests` RLS
// policy, but 0019 dropped the `skill_manifests` table entirely. On a
// post-0019 DB, 0008's DROP POLICY / CREATE POLICY statements fail with
// `relation "skill_manifests" does not exist` because Postgres's
// IF EXISTS guard on policy statements applies to the policy, not the
// underlying table. The whole migration is moot now.
//
// 0007 still creates structures in active use (session context-injection
// columns, `session_attachments`), so it stays in the list. Its
// `skill_manifests` block is a no-op on fresh DBs (0019 drops the table
// later in the same run) and remains re-runnable on established DBs
// (IF NOT EXISTS re-creates the table before the RLS block touches it).
const CUSTOM_MIGRATIONS = [
  '0002_tsvector_trigger.sql',
  '0003_rls_policies.sql',
  '0004_sessions.sql',
  '0005_mcp_connections.sql',
  '0006_document_type_column.sql',
  '0007_agents_ingestion.sql',
  '0009_session_attachments_owner_scope.sql',
  '0010_attachment_storage.sql',
  '0012_audit_events_mcp_invocation_enum.sql',
  '0013_audit_events_brain_id_column.sql',
  '0014_audit_events_realtime_publication.sql',
  '0015_mcp_in_oauth.sql',
  '0016_connectors.sql',
  '0019_skills_progressive_disclosure.sql',
];

async function main() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error('DATABASE_URL is not set');
  }

  const sql = postgres(connectionString, { max: 1 });

  try {
    for (const filename of CUSTOM_MIGRATIONS) {
      const path = resolve(__dirname, '..', 'src', 'db', 'migrations', filename);
      const content = readFileSync(path, 'utf8');

      // Split on Drizzle's statement-breakpoint marker so that statements
      // which cannot run inside a transaction (e.g. ALTER TYPE ADD VALUE)
      // are each executed in their own sql.unsafe() call.
      const blocks = content
        .split(/--> statement-breakpoint/g)
        .map((b) => b.trim())
        .filter((b) => b.length > 0);

      console.log(`Applying ${filename} (${blocks.length} block${blocks.length === 1 ? '' : 's'})...`);
      for (const block of blocks) {
        await sql.unsafe(block);
      }
      console.log(`  ✓ ${filename} applied`);
    }
  } finally {
    await sql.end();
  }
}

main().catch((err) => {
  console.error('Migration failed:', err);
  process.exit(1);
});
